version: "3.8"
services:

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  api:
    build:
      context: .
    dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data/api/database/files:/files
    restart: unless-stopped