services:
  db:
    image: postgres
    container_name: local_pgdb #use env variable
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready","-d","${POSTGRES_DB}","-h","db","-U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - ./data/api/logs:/usr/src/app/logs
      - ./data/api/data:/usr/src/app/data
    restart: unless-stopped1
    depends_on:
      db:
        condition: service_healthy