services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./data/api/database/files:/files
    restart: unless-stopped
    depends_on:
      - db
  
  nginx:
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 81:81 # admin page
      - 443:443
    volumes:
      - ./data/nginx:/data
      - ./local:/etc/letsencrypt
    depends_on:
      - api